import os
import re
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from dotenv import load_dotenv

load_dotenv()  # load env vars if present
if os.getenv("GEMINI_API_KEY"):
    os.environ["GOOGLE_API_KEY"] = os.getenv("GEMINI_API_KEY")

from rag import query_restaurants
from langchain_huggingface import HuggingFacePipeline
from transformers import pipeline
from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
from langchain_core.prompts import PromptTemplate

app = FastAPI()

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

class ChatRequest(BaseModel):
    message: str

pipe = pipeline("text2text-generation", model="google/flan-t5-small", max_new_tokens=150)
llm = HuggingFacePipeline(pipeline=pipe)

prompt_template = PromptTemplate.from_template(
    """You are a helpful gourmet guide for students.
Context:
{context}

Question: {query}
Respond nicely. At the end, put a hidden comma-separated list of 3 signature dishes like:
[DISHES: Pasta, Biryani, Chai]
"""
)

@app.post("/chat")
async def chat(req: ChatRequest):
    # 1. Retrieve context
    docs = query_restaurants(req.message, k=3)
    context_text = "\n\n".join([d.page_content for d in docs])
    
    # 2. Generate response
    chain = prompt_template | llm
    response = chain.invoke({"query": req.message, "context": context_text})

    
    # 3. Parse dishes
    dishes = []
    match = re.search(r"\[DISHES:\s*(.+?)\]", response)
    if match:
        dishes_str = match.group(1)
        dishes = [d.strip() for d in dishes_str.split(',')]
        # Remove the tag from the final chat message
        response = re.sub(r"\[DISHES:\s*(.+?)\]", "", response).strip()
    
    # If no dishes extracted, provide some defaults
    if not dishes:
         dishes = ["Basket Chaat", "Mutton Biryani", "Truffle Pasta"]
    
    images = []
    # Simplified mapping for images (will be replaced by actual images generated by tool)
    for index, dish in enumerate(dishes[:5]):
         images.append({
             "dish_name": dish,
             "image_url": f"public/images/dish_{index+1}.png"
         })

    return {
        "reply": response,
        "dishes": images
    }

if __name__ == "__main__":
    import uvicorn
    uvicorn.run(app, host="127.0.0.1", port=8000)
